### ISSUE TITLE
Av. PAR in layer (model: 'PAR', sensor: '', standard: ''') - 2-pi or 4-pi scalar

### ISSUE THREAD

**Issue by roswri** [nvs-vocabs/ereefs#1]
This parameter is described as: 'Mean scalar photosynthetically available radiation (400 - 700 nm)within the layer.'
Does 'scalar' refer to 4-pi scalar (from all directions) or 2-pi scalar (directional e.g. upwelling or downwelling)?

**Comment by sharon-tickell** [comment]
I have relayed this question to our experts on the modelling team - stay tuned for a response when they get back to me.

**Comment by sharon-tickell** [comment]
Response from the modelling team: 'scalar' is 4-pi for this one.
