### ISSUE TITLE
Coral host N (model: 'CH_N', sensor: '', standard: ''') - how is best to describe the coral host tissue

### ISSUE THREAD

**Issue by roswri** [nvs-vocabs/ereefs#10]
For the parameter: Coral host N (model: 'CH_N', sensor: '', standard: ''')
Is the coral host tissue purely the soft tissue part of the coral e.g. the polyp, only the gastrodermis, or the whole coral including the skeleton?

In the NVS which of these options (if any) is most accurate?
- coral (subcomponent: host tissue)
- coral (subcomponent: soft tissue)
- coral (subcomponent: polyp)
- coral (subcomponent: gastrodermal cells)
- just 'coral'

**Comment by markebaird** [comment]
Hi, 

CH_N does not include the skeleton. The best description would be "host tissue" 

Thanks
