### ISSUE TITLE
Macroalgae N (model: 'MA_N', sensor: '', standard: ''')

### ISSUE THREAD

**Issue by roswri** [nvs-vocabs/ereefs#12]
The description for this parameter is a little contradictory: 'Concentration of nitrogen biomass per m2 of macrolagae. Macroalgae (or seaweed) grows above all other benthic plants(corals, seagrasses, benthic microalgae). _**It is parameterised as a non-calcifying leafy algae**_, with a C:N:P ratio of 550:30:1, and a formulation for calculating the percentage of the bottom covered as1−exp(−ΩMAMA). In the model, **_in the absence of both calcifying macroalgae (particularly Halimeda) and unicellular epiphytes, macroalgae represents the biomass of all seaweeds and epiphytes._**'

If the macroalgae is specifically parameterised as non-calcifying should the parameter be mapped as:
Biomass as nitrogen of macroalgae (subgroup: non-calcifying) per unit area of the bed by model prediction

If the parameter can sometimes cover all macroalgae (including calcifying) the parameter would be mapped as:
Biomass as nitrogen of macroalgae per unit area of the bed by model prediction

**Comment by markebaird** [comment]
In most of our present application we only have one type of macroalgae which does not calcify. But the code now allows for three types (red, green or brown, with brown the default, all non-calcifying) and a future improvement might be to include calcifying in some of the algae.

In any case I would say use the second option, which accounts for nitrogen in calcifying algae, but just doesn't have the calcifying process as yet.
