### ISSUE TITLE
Is 'root' in parameters like Halophila root N (model: 'SGHROOT_N', sensor: '', standard: ''') inclusive of the rhizome?

### ISSUE THREAD

**Issue by roswri** [nvs-vocabs/ereefs#14]
Does root refer to the root only or does it also include the rhizome?

**Comment by markebaird** [comment]
Hi, 

Perhaps a better phrase would be 'underground biomass' to avoid specifying more detailed structures which as resolved by the model?

Thanks,

Mark

**Comment by roswri** [comment]
Hi @markebaird,

I've had a chat with Gwen, and we think that if the parameter includes all underground structures, the subcomponent should be created as ‘roots + rhizomes’ as this is a bit more descriptive/complete, and therefore covers all bases for users trying to search for parameters containing either roots or rhizomes. Is that alright?

Thanks,
Roseanna

**Comment by markebaird** [comment]
Ok - 'roots + rhizomes' sounds good
