### ISSUE TITLE
large/small phytoplankton/zooplankton

### ISSUE THREAD

**Issue by roswri** [nvs-vocabs/ereefs#15]
For terms such as:
Large Phytoplankton N (model: 'PhyL_N', sensor: '', standard: ''')
Small Phytoplankton N (model: 'PhyS_N', sensor: '', standard: ''')
Large Zooplankton N (model: 'ZooL_N', sensor: '', standard: ''')
Small Zooplankton N (model: 'ZooS_N', sensor: '', standard: ''')

Do the terms 'Large' and 'Small' have defined size limits? (Not a problem if not)

**Comment by markebaird** [comment]
In the model, "Large" and "Small" primarily defines who eats you (e.g. Large Zooplankton eat Large Phytoplankton, Small Zooplankton and benthic microalgae. The plankton are given a size in the parameter list, but of course this changes with model configuration.

Thanks
