### ISSUE TITLE
Simulated Fluorescence (model: 'Fluorescence', sensor: 'Chlorophyll', standard: ''')

### ISSUE THREAD

**Issue by roswri** [nvs-vocabs/ereefs#16]
How does Simulated Fluorescence (model: 'Fluorescence', sensor: 'Chlorophyll', standard: ''') differ from Total Chlorophyll (model: 'Chl_a_sum', sensor: '', standard: ''')

I think both map to 'Concentration of chlorophyll-a per unit volume of the water body by model prediction' in the NVS, unless I can specify some difference in the methodology e.g. 'by model prediction of fluorescence' or similar

**Comment by markebaird** [comment]
By 'model prediction of fluorescence' would be best. Simulated fluorescence is calculated by simulating the absorption of Chl-a in the cell and then excitation in all directions at the emission wavelengths.
