### ISSUE TITLE
Microphytobenthos N (model: 'MPB_N', sensor: '', standard: ''')

### ISSUE THREAD

**Issue by roswri** [nvs-vocabs/ereefs#17]
Defined as: Total structural biomass of nitrogen of the phytoplankton population. All microalgae have a C:N:P ratio of the structural material of 106:16:1. Thus the mass of phosphorus in the structural material of a population with a biomass B is given by: 1163114B and the mass of carbon by: 106161214B. The number of cells is given byB/mN.

two questions:

1. Would 'benthic phytoplankton' adequately cover the 'Microphytobenthos'?
2. is 'Total structural biomass of nitrogen' the same as 'Biomass as nitrogen'?

**Comment by markebaird** [comment]
Yes, benthic phytoplankton is good.

For 2., I use the phrase 'structural' to distinguish biomass of cell that is independent of nutrient status of the cell. The stored nutrient is called 'reserves'. The total nitrogen = structural + reserves.

**Comment by gwemon** [comment]
@roswri  @markebaird For me "benthic phytoplankton" is a contradiction in term. Phytoplankton organisms are expected to be in the water column when alive and phytobenthos are expected to be in the sediment when not in resuspension. I would prefer the term "microalgae".

**Comment by markebaird** [comment]
I agree, benthic microalgae is better
