### ISSUE TITLE
Material flux into the atmosphere terms

### ISSUE THREAD

**Issue by JordanAthertonNOC** [nvs-vocabs/ereefs#18]
In relation to the following two parameters (BODC sheet primary keys 39 and 40)
39 - Sea-air CO2 flux (model: 'CO2_flux', sensor: '', standard: ''')
40 - Sea-air O2 flux (model: 'O2_flux', sensor: '', standard: ''')

1) Are these gross or net fluxes of O2 and C? 
2) Would the first one more accurately be termed _flux of carbon dioxide expressed as carbon_ or _flux of carbon dioxide_?

For convenience the descriptions provided are as follows: 
Flux of carbon from sea to air (positive from sea to air). The value is given in the layer in which it was deposited (must be thicker than 20 cm), but still represents an areal flux.
Flux of oxygen from sea to air (positive from sea to air). The value is given in the layer in which it was deposited (must be thicker than 20 cm), but still represents an areal flux.

**Comment by markebaird** [comment]
1. These are net fluxes.
2. Checking the code it should be "flux of carbon dioxide expressed as carbon" - which is consistent with the units I give in the variable metadata.

**Comment by JordanAthertonNOC** [comment]
Terms ready to be created as follows:

https://github.com/nvs-vocabs/P01/issues/155
