### ISSUE TITLE
Coral host N (model: 'CH_N', sensor: '', standard: ''') - is coral the matrix?

### ISSUE THREAD

**Issue by roswri** [nvs-vocabs/ereefs#2]
This parameter is described as: 'Concentration of nitrogen biomass per m2 of coral host tissue in the entire grid cell. Unlike other epibenthic variables, corals area is assumed to exist in communities that are potentially smaller than the grid size. The fraction of the grid cell covered by corals is given by ACH. Thus the biomass in the occupied region is given by CH/ACH. The percent coverage of the coral of the bottom for the whole cell is given by ACH(1−exp(−ΩCHCH/ACH)). With only one type of coral resolved, CH represents the biomass of all symbiotic corals. Since the model contains no other benthic filter-feeders, CH best represent the sum of the biomass of all symbiotic filter-feeding organisms such as corals, sponges, clams etc. C:N:P is 106:16:1.'

Is it correct to model this as: 'Biomass as nitrogen of coral (subcomponent: host tissue) *per unit area of the bed* by model prediction'
or is 'Biomass as nitrogen *per unit area of coral (subcomponent: host tissue)* by model prediction' more accurate?

**Comment by sharon-tickell** [comment]
I have relayed this question to our experts on the modelling team - stay tuned for a response when they get back to me.

**Comment by sharon-tickell** [comment]
Response from the modelling team:  this one is "Biomass as nitrogen of coral (subcomponent: host tissue) _per unit area of the bed_ by model prediction" please.
