### ISSUE TITLE
Matrix query

### ISSUE THREAD

**Issue by JordanAthertonNOC** [nvs-vocabs/ereefs#23]
In relation to the following seven parameters:
80 - Dissolved Inorganic Nitrogen (model: 'DIN', sensor: '', standard: ''')
83 -	Dissolved Organic Carbon (model: 'DOR_C', sensor: '', standard: ''')
84 -	Dissolved Organic Nitrogen (model: 'DOR_N', sensor: '', standard: ''')
85 -	Dissolved Organic Phosphorus (model: 'DOR_P', sensor: '', standard: ''')
168 - Total C (model: 'TC', sensor: '', standard: ''')
171 - Total N (model: 'TN', sensor: '', standard: ''')
172 - Total P (model: 'TP', sensor: '', standard: ''')

Could we confirm whether the matrix for these parameters is 'water body'?

**Comment by sharon-tickell** [comment]
Yes, those are all in the water column, so matrix should be consistent with other 'water body' terms.

**Comment by JordanAthertonNOC** [comment]
Thanks @sharon-tickell
