### ISSUE TITLE
Density in Sediment, Density sediment (model: 'dens_sed', sensor: '', standard: ''')

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/ereefs#25]
R.e. the following parameter:

Density in Sediment, Density sediment (model: 'dens_sed', sensor: '', standard: ''')

Please could you clarify if we are talking about density _of_ the sediment here, i.e. the mass of a unit volume of wet sediment?

**Comment by markebaird** [comment]
This tracer probably doesn't have a meaningful value in the sediments. If it did it would be refering to the density of the porewater.

**Comment by danibodc** [comment]
Hi @markebaird 

Many thanks. I therefore propose we create this as:

Density of the sediment pore water by model prediction

**Comment by danibodc** [comment]
This term has now been loaded to P01 and will be live on the NVS from 0700: UTC tomorrow morning:

DENSMP01 - Density of the sediment pore water by model prediction

This term is now live on the NVS at https://vocab.nerc.ac.uk/collection/P01/current/DENSMP01/
