### ISSUE TITLE
Sediment porosity terms

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/ereefs#26]
R.e. the following parameters:

Sediment porosity (model: 'porosity', sensor: '', standard: ''')
Sediment porosity in Sediment, Sediment porosity sediment (model: 'porosity_sed', sensor: '', standard: ''')

1. Please could you clarify the difference between these terms? 

2. Our existing terms for porosity are modelled as below; we are assuming that your terms should be 'of wet sediment', but please could you confirm?
- Concentration of water {H2O CAS 7732-18-5} {porosity} per unit volume of sediment
- Concentration of water {H2O CAS 7732-18-5} {porosity} per unit volume of wet sediment by drying and gravimetry

**Comment by markebaird** [comment]
All tracers have a value in the water column and in either the sediment (if they are particulate) or sediment porewater (if they are dissolved). Thus porosity has a value in the water which is 1. I would suggested that we use {porosity} per unit volume of sediment.

**Comment by danibodc** [comment]
Hi @markebaird 

Many thanks. Please could you confirm if the below represents the correct matrix for each term?

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/dangar/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/dangar/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



CSIRO   Parameter | Proposed Matrix (S26)
-- | --
Sediment porosity (model: 'porosity',   sensor: '', standard: ''') | per unit volume of sediment pore water
Sediment porosity in Sediment, Sediment   porosity sediment (model: 'porosity_sed', sensor: '', standard: ''') | per unit volume of sediment



</body>

</html>


Thanks,
Dani

**Comment by markebaird** [comment]
Sediment porosity in Sediment is correct. Just checking for your readability, the value is 1 if there is no sediment and all pore water and 0 if there is no pore water and all sediment. Typically it 0.3-0.7.

Sediment porosity is a nonsensical because it is referring to sediment porosity in the water body. It's matrix should be "per unit volume of water body". I might try and remove it from the files. The model generates outputs variables XXX and XXX_sed for all tracers. But in this case porosity is not populated by the model (while porosity_sed is). Can I suggest we don't produce vocab entries for it?

**Comment by sharon-tickell** [comment]
@markebaird : noted on that explanation, and I agree we can move that one to the 'ignore' list if it's nonsensical.

**Comment by danibodc** [comment]
Ok many thanks @sharon-tickell and @markebaird! In that case, we will not create a 'Sediment porosity' term.

To match the modelling of our existing 'porosity' terms, we will model the 'Sediment porosity in sediment' term as below:

Concentration of water {H2O CAS 7732-18-5} {porosity} per unit volume of wet sediment by model prediction

Many thanks!
