### ISSUE TITLE
Vertical attenuation of heat/light

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/ereefs#28]
Vertical attenuation of heat (model: 'K_heat', sensor: '', standard: ''')
Vertical attenuation of heat in Sediment, Vertical attenuation of heat sediment (model: 'K_heat_sed', sensor: '', standard: ''')
Vert. att. at 490 nm in Sediment, Vert. att. at 490 nm sediment (model: 'Kd_490_sed', sensor: '', standard: ''')

1. Please could you confirm that the fist term relates to the water body, and the others relate to the sediment?
2. We have an existing term using 'Heat flow'. Would 'Heat flow per unit length of sediment/bed/water body' be suitable?
3. Does the 'attenuation of light' term refer to attenuation across the sediment water interface, or within the sediment. or sediment pore water?

**Comment by markebaird** [comment]
1. Yes.
2. It is not heat flow but heat attenuation.
3. Within the sediment porewater.
Thanks

**Comment by danibodc** [comment]
Many thanks @markebaird 

We will model the heat attenuation terms as follows:

Vertical attenuation of heat per unit length of wet sediment by model prediction
Vertical attenuation of heat per unit length of the water body by model prediction

We have created the vertical attenuation at 490nm term and it is live on the NVS:
https://vocab.nerc.ac.uk/collection/P01/current/ATTNMP03/
Attenuation of electromagnetic radiation (490nm wavelength) per unit length of the sediment pore water by model prediction
