### ISSUE TITLE
Absorption and Scattering terms

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/ereefs#29]
absorption at 440 (model: 'at_440', sensor: '', standard: ''')
absorption at 440 in Sediment, absorption at 440 sediment (model: 'at_440_sed', sensor: '', standard: ''')
scattering at 550 (model: 'bt_550', sensor: '', standard: ''')
scattering at 550 in Sediment, scattering at 550 sediment (model: 'bt_550_sed', sensor: '', standard: ''')

The descriptions for these terms all mention:
'...due to clear water, CDOM, microalgae and sus-pended sediments at xxx nm.'

For the terms that reference 'sediment', are we talking about absorption/scattering across/at the sediment-water interface, or within the sediment? Is this in the sediment pore water, wet sediment, or sediment?

**Comment by sharon-tickell** [comment]
My guesses are that the 'in sediment' variant is within the sediment, and more particularly in the sediment pore water, but I will need to double-check that to be certain.  Stay tuned...

**Comment by danibodc** [comment]
Ok thanks @sharon-tickell!

**Comment by markebaird** [comment]
Hi,

Sediment was a poor choice of word. How about "due to clear water, CDOM, microalgae and non-algal particles at xxx nm"

Mark

**Comment by danibodc** [comment]
Thanks @markebaird 

Would this be suitable for the absorbance terms? Would 'suspended particulate material' be expansive enough to cover 'due to clear water, CDOM, microalgae and non-algal particles at xxx nm'?

absorption at 440 in Sediment, absorption at 440 sediment (model: 'at_440_sed', sensor: '', standard: '''):
Absorbance of electromagnetic radiation (440nm wavelength) by the suspended particulate material by model prediction

absorption at 440 (model: 'at_440', sensor: '', standard: '''):
Absorbance of electromagnetic radiation (440nm wavelength) by the water body by model prediction

**Comment by markebaird** [comment]
suspended particulate matter would cover 'microalgae' and 'non-algal particulates', but CDOM is dissolved and water is itself. Could say 'due to clear water, dissolved substances and suspended particulate matter'.

**Comment by danibodc** [comment]
Hi @markebaird 

Many thanks. Is your statement above only in reference to this term:
absorption at 440 in Sediment, absorption at 440 sediment (model: 'at_440_sed', sensor: '', standard: ''') 

Or this term too:
absorption at 440 (model: 'at_440', sensor: '', standard: ''')

We need to know what distinguishes the two parameters. We cannot say 'due to clear water, dissolved substances and suspended particulate matter' for both terms, otherwise they will end up with the same label/title. 

--------------------------------------------------------------------------------------------------------------------------------------------

In relation to the scattering terms, again both descriptions mention 'Total scattering due to clear water, microalgae and suspended sediments at 550 nm', so what is the difference between the two scattering parameters and is there a difference in the matrix?

Also, are you referring to the attenuation of light due to backscatter, or is it the amount of light scattered?

I.e.

**Attenuation due to backscatter of electromagnetic radiation (xxx nm)**... in/from/by the [matrix TBD] by model prediction

Or:
**Acoustic backscatter of electromagnetic radiation (xxx nm)** in/from/by the [matrix TBD] by model prediction

Many thanks!

**Comment by markebaird** [comment]
Yes the statements do absorption at 440 nm in the water body and in the sediment should be the same. For clarity it is obviously best not to mix up the location 'sediment' with 'suspended sediment' in the water column.

**Comment by danibodc** [comment]
Hi @markebaird 

Ok we have simplified these and propose to model these as follows:

Absorbance of electromagnetic radiation (440nm wavelength) by the wet sediment {light absorption} by model prediction
Absorbance of electromagnetic radiation (440nm wavelength) by the water body {light absorption} by model prediction
Attenuation due to backscatter of electromagnetic radiation (550nm wavelength) by the wet sediment by model prediction
Attenuation due to backscatter of electromagnetic radiation (550nm wavelength) by the water body by model prediction
