### ISSUE TITLE
Concentration of inorganic particles - 8 terms

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/ereefs#3]
In relation to the following Parameter Names (CSIRO primary keys 18-25):

Dust (model: 'Dust', sensor: '', standard: ''')
FineSed (model: 'FineSed', sensor: '', standard: ''')
Gravel-carbonate (model: 'Gravel-carbonate', sensor: '', standard: ''')
Gravel-mineral (model: 'Gravel-mineral', sensor: '', standard: ''')
Mud-carbonate (model: 'Mud-carbonate', sensor: '', standard: ''')
Mud-mineral (model: 'Mud-mineral', sensor: '', standard: ''')
Sand-carbonate (model: 'Sand-carbonate', sensor: '', standard: ''')
Sand-mineral (model: 'Sand-mineral', sensor: '', standard: ''')

We propose to model the terms in the following format:
_Concentration of particles (**size class**) per unit volume of the water body by model prediction._

The physical entity 'particles' is defined in S29, which is a concatenation of an S18, S19, and S20 term. Traditionally we have specified a size range of particles in micro-metres e.g. 'particles (16000-22000um)'. 

However, here we could include info on the sinking velocities mentioned in the 'Description' tab of the spreadsheet, copied below:

**Dust** - Very small sized, re-suspending particles with a sinking velocity of 1 m d−1 and mass-specific optical properties based on observations in Gladstone Harbour.
**FineSed** - Identical to Mud-mineral, except that it is initialised to zero in the model domain, and enters only from the catchments.
**Gravel-carbonate** - Large, non-resuspending particles.
**Gravel-mineral** - Large, non-resuspending particles.
**Mud-carbonate** - Small sized, re-suspending particles with a sinking velocity of 17 m d−1, and mass-specific optical properties based on observations of suspended carbonates at Lucinda Jetty.
**Mud-mineral** - Small sized, re-suspending particles with a sinking velocity of 17 m d−1, and mass-specific optical properties based on observations in Gladstone Harbour.
**Sand-carbonate** - sized, re-suspending particles with a sinking velocity of 173 m d−1 and mass-specific optical properties based on observations of suspended carbonates at Lucinda Jetty.
**Sand-mineral** - Medium sized, re-suspending particles with a sinking velocity of 173 m d−1 and mass-specific optical properties based on observations in Gladstone Harbour.

To differentiate between the mineral and carbonate versions, the below is an example of how we could possibly structure the S29s:
**Dust** - particles (sinking velocity 1m d-1)
**Gravel-carbonate** - particles (carbonate, non-resuspending)
**Gravel-mineral** - particles (mineral, non-resuspending)
**Mud-carbonate** - particles (carbonate, sinking velocity 17m d-1)
**Mud-mineral** - particles (mineral, sinking velocity 17m d-1)
**FineSed** - particles (mineral, **_initialised to zero_**, sinking velocity 17m d-1)
**Sand-carbonate** - particles (carbonate, sinking velocity 173m d-1)
**Sand-mineral** - particles (mineral, sinking velocity 173m d-1)

Is this ok? Is this too specific to ensure re-use? Should we include the 'Sand', 'Dust', 'FineSed', etc instead? 
How would we differentiate between 'FineSed' and 'Mud-Mineral'?

**Comment by sharon-tickell** [comment]
I have relayed this question to our experts on the modelling team - stay tuned for a response when they get back to me.

**Comment by sharon-tickell** [comment]
Modelling team need to have a think about this one:  response still pending...

**Comment by sharon-tickell** [comment]
Hi Dani, this is the response I got back from the modelling team on this one:

> Including the sinking velocity, particle size, the ability to be resuspended or even how we use them in model (e.g. released from catchments, initialised to zero etc.) is non-ideal as they could limit future use. 
> 
> At the risk of being ambiguous, we could use:
> 
> Concentration of particles (size class/minerology) per unit volume of the water body by model prediction.
> 
> Dust - particles (non-carbonate, very fine)
> Gravel-carbonate - particles (carbonate, very coarse)
> Gravel-mineral - particles (non-carbonate, very coarse)
> Mud-carbonate - particles (carbonate, fine)
> Mud-mineral - particles (non-carbonate, fine)
> FineSed - particles (non-carbonate, fine)
> Sand-carbonate - particles (carbonate, coarse)
> Sand-mineral - particles (non-carbonate, very coarse)
> 
> Also, all particles have concentration in the sediments that is by volume of (sediment?) space. In our output files this is Dust_sed etc. We only do this in the output files because the sediment grid is different to the water column grid. Dust and Dust_sed are actually the same entity in different locations.

I imagine the binary carbonate vs non-carbonate  aspect should be fine - is the 'very coarse', 'coarse', 'fine', 'very fine' gradient usable?

**Comment by gwemon** [comment]
On reflection, I think that if "dust" "gravel" "mud" "sand" "fine sediment" "sand" are terms defined as part of well known scales like e.g. Wentworth then we should  keep these terms instead of very fine, fine, coarse, very coarse, unless of course the latter can be referred to a standard definition. For examples of scales see e.g. https://en.wikipedia.org/wiki/Grain_size

**Comment by nugzarm** [comment]
I agree, we can get rid of the modifier "very".
The international classification as presented in your link [https://en.wikipedia.org/wiki/Grain_size] is close to what we use in the model, though it does not map one to one.
We have Dust and FineSed missing from the classification.
Another point to mention is that sediment classes in the code are defined by the settling velocity (m/s) and the concentration (kg/m3). The size attribution is somewhat a secondary property associated with the sediments of a particular class (settling velocity) This secondary attribute is to describe further characteristics of these sediments  (but it is not used directly during the simulation).

**Comment by danibodc** [comment]
Please see the below for our proposed terms and the physical entity size class (S29, S19) definitions. If this could be reviewed and any feedback passed on that would be great.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/dangar/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/dangar/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



CSIRO   parameter | BODC pref label | BODC S29, S19 definition
-- | -- | --
Dust (model:   'Dust', sensor: '', standard: ''') | Concentration of particles (dust) per unit volume of the water   body by model prediction | Very fine particles of powdery   solid matter with very slow settling velocities in air and water.
FineSed   (model: 'FineSed', sensor: '', standard: ''') | Concentration of particles (fine-grained sediment) per unit   volume of the water body by model prediction | Fine grained particles of   unconsolidated solid matter that can be comprised of sand, silt and clay   particles of generally less than 2mm diameter. They  can be transported by the action of wind,   water, ice or gravity.
Mud-carbonate   (model: 'Mud-carbonate', sensor: '', standard: ''') | Concentration of particles (mud carbonate) per unit volume of   the water body by model prediction | The carbonate fraction of fine   grained particles of cohesive or non-cohesive solid matter comprised of   mainly silt and clay.
Mud-mineral   (model: 'Mud-mineral', sensor: '', standard: ''') | Concentration of particles (mud mineral) per unit volume of   the water body by model prediction | The non-carbonate fraction of   fine grained particles of cohesive or non-cohesive solid matter comprised of   mainly silt and clay.
Sand-carbonate   (model: 'Sand-carbonate', sensor: '', standard: ''') | Concentration of particles (sand carbonate) per unit volume of   the water body by model prediction | The carbonate fraction of   medium-sized particles of granular solid matter.
Sand-mineral   (model: 'Sand-mineral', sensor: '', standard: ''') | Concentration of particles (sand mineral) per unit volume of   the water body by model prediction | The non-carbonate fraction of   medium-sized particles of granular solid matter.
Gravel-carbonate   (model: 'Gravel-carbonate', sensor: '', standard: ''') | Concentration of particles (gravel carbonate) per unit volume   of the water body by model prediction | The carbonate fraction of large   particles of granular solid matter.
Gravel-mineral   (model: 'Gravel-mineral', sensor: '', standard: ''') | Concentration of particles (gravel mineral) per unit volume of   the water body by model prediction | The non-carbonate fraction of   large particles of granular solid matter.



</body>

</html>

**Comment by danibodc** [comment]
We have decided to express these as 'Mass concentration' which by definition is mass of a substance/constituent per unit volume of the mixture: https://github.com/nvs-vocabs/S06/issues/49

The new S29 terms listed in the table above have now been loaded - documented at https://github.com/nvs-vocabs/S29/issues/4

**Comment by danibodc** [comment]
These P01 terms have now been loaded and will be live on the NVS from tomorrow morning:

CNCPRT01	Mass concentration of particles (dust) in the sediment by model prediction
CNCPRT02	Mass concentration of particles (fine-grained sediment) in the sediment by model prediction
CNCPRT03	Mass concentration of particles (mud carbonate) in the sediment by model prediction
CNCPRT04	Mass concentration of particles (mud mineral) in the sediment by model prediction
CNCPRT05	Mass concentration of particles (sand carbonate) in the sediment by model prediction
CNCPRT06	Mass concentration of particles (sand mineral) in the sediment by model prediction
CNCPRT07	Mass concentration of particles (gravel carbonate) in the sediment by model prediction
CNCPRT08	Mass concentration of particles (gravel mineral) in the sediment by model prediction
CNCPRT09	Mass concentration of particles (dust) in the water body by model prediction
CNCPRT10	Mass concentration of particles (fine-grained sediment) in the water body by model prediction
CNCPRT11	Mass concentration of particles (mud carbonate) in the water body by model prediction
CNCPRT12	Mass concentration of particles (mud mineral) in the water body by model prediction
CNCPRT13	Mass concentration of particles (sand carbonate) in the water body by model prediction
CNCPRT14	Mass concentration of particles (sand mineral) in the water body by model prediction
CNCPRT15	Mass concentration of particles (gravel carbonate) in the water body by model prediction
CNCPRT16	Mass concentration of particles (gravel mineral) in the water body by model prediction

**Comment by danibodc** [comment]
These terms are now live on the NVS, closing ticket.

https://vocab.nerc.ac.uk/collection/P01/current/CNCPRT01/ 
https://vocab.nerc.ac.uk/collection/P01/current/CNCPRT02/
https://vocab.nerc.ac.uk/collection/P01/current/CNCPRT03/
https://vocab.nerc.ac.uk/collection/P01/current/CNCPRT04/
https://vocab.nerc.ac.uk/collection/P01/current/CNCPRT05/
https://vocab.nerc.ac.uk/collection/P01/current/CNCPRT06/
https://vocab.nerc.ac.uk/collection/P01/current/CNCPRT07/
https://vocab.nerc.ac.uk/collection/P01/current/CNCPRT08/
https://vocab.nerc.ac.uk/collection/P01/current/CNCPRT09/
https://vocab.nerc.ac.uk/collection/P01/current/CNCPRT10/
https://vocab.nerc.ac.uk/collection/P01/current/CNCPRT11/
https://vocab.nerc.ac.uk/collection/P01/current/CNCPRT12/
https://vocab.nerc.ac.uk/collection/P01/current/CNCPRT13/
https://vocab.nerc.ac.uk/collection/P01/current/CNCPRT14/
https://vocab.nerc.ac.uk/collection/P01/current/CNCPRT15/
https://vocab.nerc.ac.uk/collection/P01/current/CNCPRT16/

**Comment by sharon-tickell** [comment]
Snap - I'd just been checking those just in case, and was about to email you to let you know we were now resolving them OK.   Nice work :)

**Comment by danibodc** [comment]
No problem!

**Comment by gwemon** [comment]
Corrected the P02 Parameter Discovery group for these parameters from [MNGS](http://vocab.nerc.ac.uk/collection/P02/current/MNGS/) (relating to a sediment matrix) to [TSED](http://vocab.nerc.ac.uk/collection/P02/current/TSED/) (relating to a water body matrix)
