### ISSUE TITLE
Particulate inorganic phosphorus

### ISSUE THREAD

**Issue by JordanAthertonNOC** [nvs-vocabs/ereefs#32]
In relation to the following parameter (BODC sheet primary key 144)
144 - Particulate Inorganic Phosphorus (model: 'PIP', sensor: '', standard: ''')

Could you confirm whether the matrix for this parameter is [water body](http://vocab.nerc.ac.uk/collection/S26/current/MAT00640/) or [sediment pore water](http://vocab.nerc.ac.uk/collection/S26/current/MAT00185/).

For reference, PIP in sediment has already been requested separately:
269 | Particulate Inorganic Phosphorus in Sediment, Particulate Inorganic Phosphorus sediment (model: 'PIP_sed', sensor: '', standard: ''')

**Comment by sharon-tickell** [comment]
This one should be [water body](http://vocab.nerc.ac.uk/collection/S26/current/MAT00640/), I believe.

(only the terms with a _sed extension should be sediment/wet-sediment/sediment-pore-water)
