### ISSUE TITLE
New eReefs vocab term - diuron

### ISSUE THREAD

**Issue by sharon-tickell** [nvs-vocabs/ereefs#37]
Hi BODC team - we have our first new eReefs parameter to be added since the main bunch, to be counted as one of the 10 points-worth of new P01 parameters in the current support year.

The parameter name is 'diuron', and it's representing the concentration of the pesticide Diuron in the seawater column, with units of 'mg m-3'.   Generated by model simulation (similar to the other other model parameters last year).    We are not currently modelling the diuron in sediment, so no need for a matching 'in sediment' term. 

There's some information about diuron and it's reglated use in the GBR catchments at https://apvma.gov.au/node/12511

**Comment by sharon-tickell** [comment]
And more context for how this parameter is used in the model: https://marlin.csiro.au/geonetwork/srv/eng/catalog.search#/metadata/aefc4227-8779-47a8-9137-2839631f9328

**Comment by JordanAthertonNOC** [comment]
Hi @sharon-tickell 

Would you like this term to include detail of phase, two suggestions as follows:

1) Concentration of diuron {3-(3,4-dichlorophenyl)-1,1-dimethylurea CAS 330-54-1} per unit volume of the water body by model prediction
2) Concentration of diuron {3-(3,4-dichlorophenyl)-1,1-dimethylurea CAS 330-54-1} per unit volume of the water body [dissolved plus reactive particulate phase] by model prediction

Best

Jordan

**Comment by sharon-tickell** [comment]
Hi @JordanAthertonNOC : apologies for my delayed response. I have confirmation now from the modeller that the first option of your list with no detail of phase is the correct one: 

**Concentration of diuron {3-(3,4-dichlorophenyl)-1,1-dimethylurea CAS 330-54-1} per unit volume of the water body by model prediction**

**Comment by JordanAthertonNOC** [comment]
No problem, thanks @sharon-tickell, I'll get to work on this now.

**Comment by JordanAthertonNOC** [comment]
Hi @sharon-tickell, one new P01 code has been created and will appear online after ~07:30 GMT tomorrow.

[CDIURMD1](http://vocab.nerc.ac.uk/collection/P01/current/CDIURMD1/)

**Comment by sharon-tickell** [comment]
Excellent - thanks @JordanAthertonNOC 
I can access that new term link (and it's PUV profile equivalent) with no problems. Looks great.
