### ISSUE TITLE
Modis-KD490 (model: 'KD490M', sensor: '', standard: ''') - is this a duplicate?

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/ereefs#4]
Is: 
Modis-KD490 (model: 'KD490M', sensor: '', standard: ''') 

a duplicate of: 
Vert. att. at 490 nm  (model: 'Kd_490', sensor: '', standard: ''')?

Is there any difference or can one be crossed off the list?

**Comment by sharon-tickell** [comment]
Hi @danibodc: I've double checked our notes from when we assembled the parameter list, and can confirm that:

- KD490M appears with a description of ‘Modis-KD490’ in the results from these model versions:
	- <GBR4_H2p0_B3p1_Cq3P_Dhnd-agg>
	- <GBR4_H2p0_B3p1_Cq3R_Dhnd-agg>
	- <GBR4_H2p0_B3p1_Cq3b_Dhnd-agg>
	- <gbr4_bgc_GBR4_H2p0_B2p0_Chyd_Dcrt>
	- <gbr4_bgc_GBR4_H2p0_B2p0_Chyd_Dnrt> 
	- <gbr4_bgc_GBR4_H2p0_B2p0_Cpre_Dcrt>
	- <gbr4_bgc_GBR4_H2p0_B2p0_Cpre_Dnrt>

- Kd490 appears with a description of ‘MODIS Kd490’ in two much older model versions:
    - <gbr4_bgc_924>,
    - <gbr4_bgc_926>
	
-	And Kd_490 appears with a description of ‘Vert. att. at 490 nm’ in all of them, AND has an entry in the formally published descriptions of the model parameters.
	- <GBR4_H2p0_B3p1_Cq3P_Dhnd-agg>
	- <GBR4_H2p0_B3p1_Cq3R_Dhnd-agg>
	- <GBR4_H2p0_B3p1_Cq3b_Dhnd-agg> 
	- <gbr4_bgc_924>
	- <gbr4_bgc_926>
	- <gbr4_bgc_GBR4_H2p0_B2p0_Chyd_Dcrt>
	- <gbr4_bgc_GBR4_H2p0_B2p0_Chyd_Dnrt>
	- <gbr4_bgc_GBR4_H2p0_B2p0_Cpre_Dcrt>
	- <gbr4_bgc_GBR4_H2p0_B2p0_Cpre_Dnrt>


So my take on that is that KD490M and Kd490 are actually the same thing (representing a simulation of what MODIS would see, and with KD490M as the correct variant of the parameter name), but Kd_490 is different. and we need to keep both.

I've sent the question off to our modelling team, and will await their confirmation before saying that's definitely the answer, though!

**Comment by danibodc** [comment]
Ok thank you for that @sharon-tickell! If Kd_490 is different, we will need to be really clear on what the differences are so that we can capture this unambiguously in the parameter labels and descriptions for both parameters. Will wait to hear more from the modelling team!

**Comment by sharon-tickell** [comment]
Confirmation received from the modellers:   my hypothesis was correct, and KD490M and Kd_490 are definitely seperate parameters, so we will need two different P01 terms.

The 'M-for Modis' in the KD490 parameter name means that the model is calculating what it thinks the MODIS satellite sensor will see, so the P01 construct should use the same pattern for that one as will be used for OC3M, OC3V and OC4Me.

**Comment by danibodc** [comment]
Ok that's great, thank you @sharon-tickell!
