### ISSUE TITLE
Parameters relating to nitrogen biomass of benthic plants

### ISSUE THREAD

**Issue by roswri** [nvs-vocabs/ereefs#5]
- Macroalgae N (model: 'MA_N', sensor: '', standard: '''), Description: Concentration of nitrogen biomass per m2 of macrolagae'
- Seagrass N (model: 'SG_N', sensor: '', standard: '''), Description: 'Concentration of nitrogen biomass per m2 of a seagrass form parameterised to be similar to Zostera.'
- Deep seagrass N (model: 'SGD_N', sensor: '', standard: '''), Description: 'Concentration of nitrogen biomass per m2 of a seagrass form parameterised to be similar to Halophila deciphens.'
- Halophila N (model: 'SGH_N', sensor: '', standard: '''), Description:  'Concentration of nitrogen biomass per m2 of a seagrass form parameterised to be similar to Halophila ovalis.'

Is the benthic plant the matrix (e.g. Biomass as nitrogen per unit area of the macroalgae by model prediction) or is it per unit area of the bed (e.g. Biomass as nitrogen of macroalgae per unit area of the bed by model prediction)

Previous issues seem to suggest 'per unit area of the bed' is correct:
https://github.com/nvs-vocabs/P01/issues/43
https://github.com/nvs-vocabs/P01/issues/44
https://github.com/nvs-vocabs/P01/issues/46
https://github.com/nvs-vocabs/P01/issues/45

However, the similar coral parameter raised some doubts: https://github.com/nvs-vocabs/ereefs/issues/2

**Comment by sharon-tickell** [comment]
I have relayed this question to our experts on the modelling team - stay tuned for a response when they get back to me.

**Comment by sharon-tickell** [comment]
Relaying the from the modellers:  these ones are all "per unit area of the bed" please.
