### ISSUE TITLE
PH (model: 'PH', sensor: 'pH', standard: ''') - which pH scale?

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/ereefs#6]
Regarding your pH term:
PH (model: 'PH', sensor: 'pH', standard: '''), which pH scale has been used here?

I have made the assumption that this is referencing the free scale:
Free scale - http://vocab.nerc.ac.uk/collection/S06/current/S0600278

As your definition mentions pH is based on the H+ ion concentration:
pH based on [H+] calculated from carbon chemistry equilibra at water column values of T,S,DIC and AT.

Please could you confirm if this is correct, as there are 3 other possible pH scales as below:
NBS Scale - http://vocab.nerc.ac.uk/collection/S06/current/S0600280
Total Scale - http://vocab.nerc.ac.uk/collection/S06/current/S0600277
Seawater scale - http://vocab.nerc.ac.uk/collection/S06/current/S0600279

If you are not certain which scale has been used, we are able to use 'unspecified scale':
http://vocab.nerc.ac.uk/collection/S06/current/S0600281

Many thanks!

**Comment by markebaird** [comment]
Total

**Comment by markebaird** [comment]
i.e. Total Scale.

**Comment by danibodc** [comment]
Brilliant, thank you!
