### ISSUE TITLE
Chlorophyll vs chlorophyll-a parameters

### ISSUE THREAD

**Issue by JordanAthertonNOC** [nvs-vocabs/ereefs#7]
In relation to the following four parameters (BODC sheet primary keys 1; 42:44)
01 - Total Chlorophyll (model: 'Chl_a_sum', sensor: '', standard: ''')
42 - MODIS OC3 algorithm (model: 'OC3M', sensor: 'Chlorophyll', standard: ''')
43 - VIIRS-OC3V (model: 'OC3V', sensor: 'Chlorophyll', standard: ''')
44 - MERIS OC4 algorithm (model: 'OC4Me', sensor: 'Chlorophyll', standard: ''')

Seeking clarification from the modelling team as to whether the terms we create should refer to chlorophyll or chlorophyll-a.

For parameters 42:44, chl vs chl-a is signposted by the units, but thought it best to double check these before locking them in!

**Comment by markebaird** [comment]
chlorophyll-a in the case of Total Chlorophyll, Large Phytoplankton Chlorophyll, Small Phytoplankton Chlorophyll etc.

In terms of the modelled satellite algorithms (OC3M, OC3V, OC4Me), use similar descriptions of the respective satellite products are in your vocabulary.

**Comment by sharon-tickell** [comment]
I don't think we have descriptions of the satellite products in there yet, do we @JordanAthertonNOC ?   If not, I'll relay this particular one on to our Remote Sensing people for confirmation on the satellite algorithms.

**Comment by markebaird** [comment]
I meant the descriptions of satellite products that I presume are in the vocabs already for other uses.

Basically, we are trying to calculate exactly the same quantity as the NASA MODIS OC3 algorithm, except by means of a numerical model, not a radiometer stuck on a satellite.

**Comment by sharon-tickell** [comment]
Yep - it's that "presume are in the vocabs already for other uses" bit that I'm not quite sure is an accurate presumption just yet!

**Comment by JordanAthertonNOC** [comment]
At present I have the three satellite product parameters as follows (with MODIS and MERIS as chlorophyll, and VIIRS as chlorophyll-a), but this is purely based on the units provided rather than me looking into the satellite outputs and/or algorithms: 

44 - Concentration of **chlorophyll** per unit volume of the water body by model prediction of Moderate Resolution Imaging Spectroradiometer (MODIS) output and computation using the OC3M algorithm

45 - Concentration of **chlorophyll-a** per unit volume of the water body by model prediction of Visible Infrared Imaging Radiometer Suite (VIIRS) output and computation using the published OC3V algorithm

46 - Concentration of **chlorophyll** per unit volume of the water body by model prediction of Medium Resolution Imaging Spectrometer (MERIS) output and computation using the published OC4Me algorithm

The satellite product and algorithm components of the parameter are covered in the S04 (analysis) and S05 (data processing) collections respectively. We do have an existing entry in our S05 catalogue for OC5 (https://vocab.nerc.ac.uk/collection/S05/current/S050027/) with two linked parameters for MERIS and MODIS outputs which we can use as an analogue. However both linked terms refer to chlorophyll-a which contrasts the units provided for these satellite products in the original CSIRO spreadsheet.

**Comment by sharon-tickell** [comment]
Some relevant references, I think

- MODIS OC3 references => Chlorophyll-a for that one
  - https://researchdata.edu.au/imos-srs-modis-oc3-model/955075 
  - https://oceancolor.gsfc.nasa.gov/atbd/chlor_a/
- VIIRS OC3V => Chlorophyll-a
  -  https://eastcoast.coastwatch.noaa.gov/cw_viirs_chl.php
- MERIS OC4 => Chlorophyll concentration...
  - This one has just Chl, and ought to be the authoritative reference, I think!   https://sentinels.copernicus.eu/web/sentinel/technical-guides/sentinel-3-olci/level-2/oc4me-chlorophyll
  - And this paper (https://www.researchgate.net/publication/324866198_Statistical_modelling_of_MERIS_Chlorophyll_OC4Me) says "The OC4Me algorithm is the total chlorophyll concentration (TChla) determined through a polynomial regression based on multiple band ratios of MERIS normalized water-leaving reflectances (also known as the standard Algal Pigment Index 1 (API1)). The TChla comprises the sum of monovinyl chlorophyll-a, divinyl chlorophyll-a, chlorophyllide, and phaeophytin-a."
  
Also:
- https://imos.org.au/fileadmin/user_upload/shared/SRS/ocean_colour/IMOS_OC_Validation_Report_2015-16_Final_Upload.pdf

**Comment by sharon-tickell** [comment]
Some clarification from an actual remote sensing expert (Thomas Schroeder, who is leading that bit of eReefs):

> The satellite is not measuring chlorophyll-a (chl-a). The chlorophyll-a is derived from the surface marine reflectance. These algorithms are very simple and based on band-ratios, which work fine for open ocean waters but not for coastal waters. OC3 used 3 bands, while OC4 requires 4 bands as input. Basically the number indicates how many bands are used (2-4). 
> Reference for OC3 is (copy attached): 
> O'Reilly J. E., Maritorena S., Siegel D., O'Brien M. O., Toole D., Mitchell B. G., Kahru M., Chavez F. P., Strutton P., Cota G. F., Hooker S. B., McClain C. R., Carder K. L., Muller‐Karger F., Harding L., Magnuson A., Phinney D., Moore G. F., Aiken J., Arrigo K. R., Letelier R. M., Culver M. (2000), Ocean Color Chlorophyll a Algorithms for SeaWiFS, OC2, and OC4: Version 4, In SeaWiFS Postlaunch Calibration and Validation Analyses, Volume 11, Part 3, (McClain C. R., Ed.), pages 9‐23, Greenbelt, Md.: Goddard Space Flight Center.
> See also details and references provided at:
> https://oceancolor.gsfc.nasa.gov/atbd/chlor_a/
> Specifically the table overview in section 2.
> Cheers Thomas
> 
[PLVol11.pdf](https://github.com/nvs-vocabs/ereefs/files/8470837/PLVol11.pdf)

**Comment by JordanAthertonNOC** [comment]
Settled on chlorophyll-a for all satellite product terms.
