### ISSUE TITLE
Coral symbiont N (model: 'CS_N', sensor: '', standard: ''')

### ISSUE THREAD

**Issue by JordanAthertonNOC** [nvs-vocabs/ereefs#9]
In relation to the following parameter (BODC sheet primary key 7)
07 - Coral symbiont N (model: 'CS_N', sensor: '', standard: ''')

The CSIRO description provided is: "Concentration of nitrogen biomass per m2 of coral symbiont cells, or zooxanthellae."

Does this parameter strictly refer to the algal component of coral or does it refer to both the animal and algal components?

**Comment by markebaird** [comment]
Just the algal component.

Thanks, Mark

**Comment by JordanAthertonNOC** [comment]
Thanks Mark.
